version: '3.4'

services:
  socialform_web_app:
    image: socialform_web_app
    container_name: socialform_web_app
    build:
      context: .
      dockerfile: ./socialform_web_app/Dockerfile
    stdin_open: true
    ports:
      - 3001:3000
    volumes:
      - './socialform_web_app:/app'
    environment:
      - CHOKIDAR_USEPOLLING=true

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile

  postservice:
    image: ${DOCKER_REGISTRY-}postservice
    build:
      context: .
      dockerfile: PostService/Dockerfile
    depends_on:
      - socialform_web_app

  imageapi:
    image: ${DOCKER_REGISTRY-}imageapi
    build:
      context: .
      dockerfile: ImageApi/Dockerfile
    volumes:
      - ./ImageApi/UploadImages:/app/UploadImages


  likeservice:
    image: ${DOCKER_REGISTRY-}likeservice
    build:
      context: .
      dockerfile: LikeService/Dockerfile


  commentservice:
    image: ${DOCKER_REGISTRY-}commentservice
    build:
      context: .
      dockerfile: CommentService/Dockerfile
